# Project information

site_name: Build a Vulnerability Management Program Using AWS for AWS
site_short_name: Vulnerability Management
site_description: 'This hands-on workshop is where you will learn about a number of AWS services involved with threat detection and response as we walk through real-world threat scenarios. Learn about the threat detection capabilities of Amazon GuardDuty, Amazon Macie and AWS Security Hub and the available response options. For each hands-on scenario, we review methods to detect and respond to threats using the following services: AWS CloudTrail, Amazon VPC flow logs, Amazon CloudWatch Events, Amazon Macie, AWS Lambda, Amazon Inspector, Amazon GuardDuty and Amazon Security Hub.'
site_author: 'aws-security-workshops@amazon.com'
site_url: 'https://vul-mgmt-program.awssecworkshops.com/'

# Repository
repo_name: 'aws-samples/aws-vulnerability-management-workshop'
repo_url: 'https://github.com/aws-samples/aws-vulnerability-management-workshop'

# Copyright
copyright: '<a href="https://aws.amazon.com/privacy/" target="_blank">Privacy</a> | <a href="https://aws.amazon.com/terms/" target="_blank">Site terms</a> | &copy; 2020, Amazon Web Services, Inc. or its affiliates. All rights reserved.'

# Configuration
theme:
  name: 'material'
  logo: 'assets/images/aws_smile_logo.png'
  favicon: 'assets/images/aws-favicon.ico'

# Customization
extra_css:
  - 'stylesheets/custom.css'
extra:
  social:
    - icon: fontawesome/solid/home
      link: https://awssecworkshops.com
    - icon: fontawesome/solid/shield-alt
      link: https://aws.amazon.com/security/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/awssecurityinfo?lang=en
    - icon: fontawesome/solid/rss-square
      link: https://aws.amazon.com/blogs/security/

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details

# Navigation
nav:
  - Overview: 'index.md'
  - 'Module 1: Asset Management': 'module1/index.md'
  - 'Module 2: AMI Factory': 'module2/index.md'
  - 'Module 3: Vulnerability Assessment': 'module3/index.md'
  - 'Module 4: Fleet Management at Scale': 'module4/index.md'
  - Contributing: 'contribute.md'
  - License: 'license.md'
